name: improc_beginner
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - pandas
  - jupyter_contrib_nbextensions
  - ipyvolume
  - ipympl
  - pip:
    - requests