name: improc_beginner
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - numpy
  - matplotlib
  - scikit-image
  - jupyter
  - jupyterlab=1.2
  - ipywidgets
  - pandas
  - nodejs
  - jupyter_contrib_nbextensions
  - ipyvolume
  - ipympl
  - pip:
    - requests