name: improc_beginner_corr
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - pandas
  - jupyter_contrib_nbextensions
  - ipympl
  - nbgrader
  - pip:
    - requests
    - lckr-jupyterlab-variableinspector